import os

import requests

API_TOKEN = os.environ.get("HUGGINGFACEHUB_API_TOKEN")
API_URL = (
    "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"
)
REQUEST_TIMEOUT = (5, 30)
UNAVAILABLE_MESSAGE = (
    "AI recommendations are unavailable. Check the inference service configuration "
    "or try again later."
)


def _clean_response(generated_text, prompt):
    """
    Cleans the generated text by removing the specified prompt and any special tokens.

    Args:
        generated_text (str): The text generated by the model which may contain the prompt and special tokens.
        prompt (str): The prompt text that needs to be removed from the generated text.

    Returns:
        str: A cleaned version of the generated text with the prompt and special tokens removed.
    """
    cleaned = generated_text.replace(prompt, "").strip()
    cleaned = cleaned.replace("<s>", "").replace("</s>", "").strip()
    return "\n".join([line.strip() for line in cleaned.split("\n") if line.strip()])


def generate_network_failure_recommendations(network_data, weather_data):
    """
    Generates network failure recommendations based on network performance metrics and weather conditions.

    Args:
        network_data (dict): Dictionary containing key network metrics.
            - Packet_Loss (float): Packet loss percentage.
            - Latency (float): Latency in milliseconds.
            - Jitter (float): Jitter in milliseconds.
            - Bandwidth_Usage (float): Bandwidth usage in percentage.
        weather_data (dict): Dictionary containing real-time weather conditions.
            - Temperature (float): Temperature in Celsius.
            - Humidity (float): Humidity percentage.
            - Condition (str): Weather condition (e.g., Rain, Storm, Clear).
    Returns:
        str: Generated recommendations, or an availability message when the
            inference request fails or returns an unusable response.
    """

    prompt = f"""
    Analyze the following network and weather data to assess potential network failures:

    - Network Metrics:
      - Packet Loss: {network_data["Packet_Loss"]}%
      - Latency: {network_data["Latency"]} ms
      - Jitter: {network_data["Jitter"]} ms
      - Bandwidth Usage: {network_data["Bandwidth_Usage"]}%

    - Weather Conditions:
      - Temperature: {weather_data["temperature"]}°C
      - Humidity: {weather_data["humidity"]}%
      - Condition: {weather_data["condition"]}

    Given this data, provide **three specific recommendations** to prevent or mitigate network failures. 
    Format the recommendations as a **numbered list** with no extra commentary.
    """

    headers = {"Authorization": f"Bearer {API_TOKEN}"}
    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 300,
            "temperature": 0.7,
            "return_full_text": False,
        },
    }

    try:
        response = requests.post(
            API_URL, headers=headers, json=payload, timeout=REQUEST_TIMEOUT
        )
        response.raise_for_status()
        result = response.json()
    except (requests.RequestException, ValueError):
        # Do not display provider errors: they may contain sensitive request data.
        return UNAVAILABLE_MESSAGE

    if not isinstance(result, list) or not result or not isinstance(result[0], dict):
        return UNAVAILABLE_MESSAGE
    generated_text = result[0].get("generated_text")
    if not isinstance(generated_text, str):
        return UNAVAILABLE_MESSAGE
    return _clean_response(generated_text, prompt) or UNAVAILABLE_MESSAGE
